apiVersion: v1
kind: Service
metadata:
  labels:
    app: codename
    codename: "true"
  name: codename
spec:
  ports:
    - name: http
      port: 8080
      targetPort: http
  selector:
    app: codename
